//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_HighGroundControlSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GripButton
        {
            get
            {
                return SteamVR_Actions.highGroundControlSet_GripButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerButton
        {
            get
            {
                return SteamVR_Actions.highGroundControlSet_TriggerButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadButton
        {
            get
            {
                return SteamVR_Actions.highGroundControlSet_TrackpadButton;
            }
        }
        
        public virtual SteamVR_Action_Pose HandPos
        {
            get
            {
                return SteamVR_Actions.highGroundControlSet_HandPos;
            }
        }
        
        public virtual SteamVR_Action_Vibration Rumble
        {
            get
            {
                return SteamVR_Actions.highGroundControlSet_Rumble;
            }
        }
    }
}
