//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_High_GroundControlSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabButton
        {
            get
            {
                return SteamVR_Actions.high_GroundControlSet_GrabButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadClick
        {
            get
            {
                return SteamVR_Actions.high_GroundControlSet_TrackpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.high_GroundControlSet_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Pose HandPos
        {
            get
            {
                return SteamVR_Actions.high_GroundControlSet_HandPos;
            }
        }
    }
}
