//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_highGroundControlSet_GripButton;
        
        private static SteamVR_Action_Boolean p_highGroundControlSet_TriggerButton;
        
        private static SteamVR_Action_Boolean p_highGroundControlSet_TrackpadButton;
        
        private static SteamVR_Action_Pose p_highGroundControlSet_HandPos;
        
        private static SteamVR_Action_Vibration p_highGroundControlSet_Rumble;
        
        public static SteamVR_Action_Boolean highGroundControlSet_GripButton
        {
            get
            {
                return SteamVR_Actions.p_highGroundControlSet_GripButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean highGroundControlSet_TriggerButton
        {
            get
            {
                return SteamVR_Actions.p_highGroundControlSet_TriggerButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean highGroundControlSet_TrackpadButton
        {
            get
            {
                return SteamVR_Actions.p_highGroundControlSet_TrackpadButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose highGroundControlSet_HandPos
        {
            get
            {
                return SteamVR_Actions.p_highGroundControlSet_HandPos.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration highGroundControlSet_Rumble
        {
            get
            {
                return SteamVR_Actions.p_highGroundControlSet_Rumble.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.highGroundControlSet_GripButton,
                    SteamVR_Actions.highGroundControlSet_TriggerButton,
                    SteamVR_Actions.highGroundControlSet_TrackpadButton,
                    SteamVR_Actions.highGroundControlSet_HandPos,
                    SteamVR_Actions.highGroundControlSet_Rumble};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.highGroundControlSet_GripButton,
                    SteamVR_Actions.highGroundControlSet_TriggerButton,
                    SteamVR_Actions.highGroundControlSet_TrackpadButton,
                    SteamVR_Actions.highGroundControlSet_HandPos};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.highGroundControlSet_Rumble};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.highGroundControlSet_Rumble};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.highGroundControlSet_HandPos};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.highGroundControlSet_GripButton,
                    SteamVR_Actions.highGroundControlSet_TriggerButton,
                    SteamVR_Actions.highGroundControlSet_TrackpadButton};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.highGroundControlSet_GripButton,
                    SteamVR_Actions.highGroundControlSet_TriggerButton,
                    SteamVR_Actions.highGroundControlSet_TrackpadButton};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_highGroundControlSet_GripButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HighGroundControlSet/in/GripButton")));
            SteamVR_Actions.p_highGroundControlSet_TriggerButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HighGroundControlSet/in/TriggerButton")));
            SteamVR_Actions.p_highGroundControlSet_TrackpadButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/HighGroundControlSet/in/TrackpadButton")));
            SteamVR_Actions.p_highGroundControlSet_HandPos = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/HighGroundControlSet/in/HandPos")));
            SteamVR_Actions.p_highGroundControlSet_Rumble = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/HighGroundControlSet/out/Rumble")));
        }
    }
}
