//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_high_GroundControlSet_GrabButton;
        
        private static SteamVR_Action_Boolean p_high_GroundControlSet_TrackpadClick;
        
        private static SteamVR_Action_Boolean p_high_GroundControlSet_TriggerClick;
        
        private static SteamVR_Action_Pose p_high_GroundControlSet_HandPos;
        
        private static SteamVR_Action_Boolean p_high_GroundControlSet_HeadsetOn;
        
        private static SteamVR_Action_Vibration p_high_GroundControlSet_Haptic;
        
        public static SteamVR_Action_Boolean high_GroundControlSet_GrabButton
        {
            get
            {
                return SteamVR_Actions.p_high_GroundControlSet_GrabButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean high_GroundControlSet_TrackpadClick
        {
            get
            {
                return SteamVR_Actions.p_high_GroundControlSet_TrackpadClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean high_GroundControlSet_TriggerClick
        {
            get
            {
                return SteamVR_Actions.p_high_GroundControlSet_TriggerClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose high_GroundControlSet_HandPos
        {
            get
            {
                return SteamVR_Actions.p_high_GroundControlSet_HandPos.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean high_GroundControlSet_HeadsetOn
        {
            get
            {
                return SteamVR_Actions.p_high_GroundControlSet_HeadsetOn.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration high_GroundControlSet_Haptic
        {
            get
            {
                return SteamVR_Actions.p_high_GroundControlSet_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.high_GroundControlSet_GrabButton,
                    SteamVR_Actions.high_GroundControlSet_TrackpadClick,
                    SteamVR_Actions.high_GroundControlSet_TriggerClick,
                    SteamVR_Actions.high_GroundControlSet_HandPos,
                    SteamVR_Actions.high_GroundControlSet_HeadsetOn,
                    SteamVR_Actions.high_GroundControlSet_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.high_GroundControlSet_GrabButton,
                    SteamVR_Actions.high_GroundControlSet_TrackpadClick,
                    SteamVR_Actions.high_GroundControlSet_TriggerClick,
                    SteamVR_Actions.high_GroundControlSet_HandPos,
                    SteamVR_Actions.high_GroundControlSet_HeadsetOn};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.high_GroundControlSet_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.high_GroundControlSet_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.high_GroundControlSet_HandPos};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.high_GroundControlSet_GrabButton,
                    SteamVR_Actions.high_GroundControlSet_TrackpadClick,
                    SteamVR_Actions.high_GroundControlSet_TriggerClick,
                    SteamVR_Actions.high_GroundControlSet_HeadsetOn};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.high_GroundControlSet_GrabButton,
                    SteamVR_Actions.high_GroundControlSet_TrackpadClick,
                    SteamVR_Actions.high_GroundControlSet_TriggerClick,
                    SteamVR_Actions.high_GroundControlSet_HeadsetOn};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_high_GroundControlSet_GrabButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/High_GroundControlSet/in/GrabButton")));
            SteamVR_Actions.p_high_GroundControlSet_TrackpadClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/High_GroundControlSet/in/TrackpadClick")));
            SteamVR_Actions.p_high_GroundControlSet_TriggerClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/High_GroundControlSet/in/TriggerClick")));
            SteamVR_Actions.p_high_GroundControlSet_HandPos = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/High_GroundControlSet/in/HandPos")));
            SteamVR_Actions.p_high_GroundControlSet_HeadsetOn = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/High_GroundControlSet/in/HeadsetOn")));
            SteamVR_Actions.p_high_GroundControlSet_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/High_GroundControlSet/out/Haptic")));
        }
    }
}
