//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_HighGroundControlSet p_HighGroundControlSet;
        
        public static SteamVR_Input_ActionSet_HighGroundControlSet HighGroundControlSet
        {
            get
            {
                return SteamVR_Actions.p_HighGroundControlSet.GetCopy<SteamVR_Input_ActionSet_HighGroundControlSet>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_HighGroundControlSet = ((SteamVR_Input_ActionSet_HighGroundControlSet)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_HighGroundControlSet>("/actions/HighGroundControlSet")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.HighGroundControlSet};
        }
    }
}
